# 01. 선형회귀

## 기본 셋팅

In [43]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## optimizer.zero_grad()가 필요한 이유
grad가 계속 누적되기 때문

In [35]:
import torch
w=torch.tensor(2.0,requires_grad=True)

nb_epochs=20
for epoch in range(nb_epochs+1):
    z=2*w
    z.backward()
    print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
수식을 w로 미분한 값: 42.0


## torch.manual_seed()를 하는 이유
다른 컴퓨터에서 실행했을 때도 동일한 결과를 얻어내기 위해서

In [36]:
import torch

In [37]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [40]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [42]:
torch.manual_seed(3)
print('랜덤 시드가 다시 3일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


# 02. 자동 미분(Autograd)
경사하강법을 직접 코딩하는 것은 까다로움. 파이토치에서 그래서 자동 미분을 지원함. requires_grad=True, backward() 가 자동미분을 수행하는 것임.

In [44]:
import torch

In [46]:
w=torch.tensor(2.0, requires_grad=True) # 텐서에 대한 기울기를 저장하겠다는 뜻

y=w**2
z=2*y+5

z.backward() #해당 수식(z)의 w(requires_grad로 지정됨)에 대한 기울기 계산

print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


# 03. 다중 선형 회귀 (Multivariable Linear Regression)

In [47]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [48]:
x1_train=torch.FloatTensor([[73],[93],[89],[96],[73]]) # Quiz1
x2_train=torch.FloatTensor([[80],[88],[91],[98],[66]]) # Quiz2
x3_train=torch.FloatTensor([[75],[93],[90],[100],[70]]) # Quiz3
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [49]:
w1=torch.zeros(1,requires_grad=True)
w2=torch.zeros(1, requires_grad=True)
w3=torch.zeros(1, requires_grad=True)
b=torch.zeros(1, requires_grad=True)

In [51]:
optimizer = optim.SGD([w1,w2,w3,b],lr=1e-5)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    hypothesis=x1_train*w1+x2_train*w2+x3_train*w3+b
    
    cost=torch.mean((hypothesis-y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))

Epoch    0/1000 w1: 0.459 w2: 0.458 w3: 0.464 b: 0.005 Cost: 9298.520508
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.562946
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.496967
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.434433
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375144
Epoch  500/1000 w1: 0.695 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.318964
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.265695
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215217
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167346
Epoch  900/1000 w1: 0.714 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.121989
Epoch 1000/1000 w1: 0.718 w2: 0.612 w3: 0.680 b: 0.009 Cost: 1.078964


## 벡터와 행렬 연산으로 바꾸기

In [24]:
x_train=torch.FloatTensor([[73,80,75],
                          [93,88,93],
                          [89,91,90],
                          [96,98,100],
                          [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [52]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [53]:
W=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [55]:
optimizer=optim.SGD([W,b],lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
    hypothesis=x_train.matmul(W)+b
    
    cost=torch.mean((hypothesis-y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch,nb_epochs,hypothesis.squeeze().detach(),cost.item()))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371063
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

# 04. nn.Module로 구현하는 선형 회귀

In [41]:
# import torch.nn as nn
# model=nn.Linear(input_dim, output_dim)

# import torch.nn.functional as F
# cost=F.mse_loss(prediction, y_train)

## 04-1 단순 선형회귀

In [61]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [62]:
torch.manual_seed(1)

In [65]:
model=nn.Linear(1,1)
print(list(model.parameters()))
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [66]:
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

In [70]:
nb_epochs=2000
for epoch in range(nb_epochs + 1):
        
    prediction=model(x_train)
    
    cost=F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('Epoch {:4d}/{} Cost {:6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost 14.714844
Epoch  100/2000 Cost 0.127436
Epoch  200/2000 Cost 0.078748
Epoch  300/2000 Cost 0.048661
Epoch  400/2000 Cost 0.030070
Epoch  500/2000 Cost 0.018581
Epoch  600/2000 Cost 0.011482
Epoch  700/2000 Cost 0.007095
Epoch  800/2000 Cost 0.004384
Epoch  900/2000 Cost 0.002709
Epoch 1000/2000 Cost 0.001674
Epoch 1100/2000 Cost 0.001035
Epoch 1200/2000 Cost 0.000639
Epoch 1300/2000 Cost 0.000395
Epoch 1400/2000 Cost 0.000244
Epoch 1500/2000 Cost 0.000151
Epoch 1600/2000 Cost 0.000093
Epoch 1700/2000 Cost 0.000058
Epoch 1800/2000 Cost 0.000036
Epoch 1900/2000 Cost 0.000022
Epoch 2000/2000 Cost 0.000014


## 04-2 다중 선형 회귀 구현하기

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
# x_train=torch.FloatTensor([[73,80,75],
#                           [93,88,93],
#                           [89,91,90],
#                           [96,98,100],
#                           [73,66,70]])
x_train=torch.FloatTensor([[3,6],
                          [2,5],
                          [4,3]])
# y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
y_train=torch.FloatTensor([[18],[12],[14]])

In [4]:
model=nn.Linear(2,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True), Parameter containing:
tensor([-0.1371], requires_grad=True)]


In [19]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=100000
for epoch in range(nb_epochs+1):
    
    prediction=model(x_train)
    
    cost=F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs,cost.item()))

Epoch    0/100000 Cost: 0.800683
Epoch  100/100000 Cost: 0.800369
Epoch  200/100000 Cost: 0.800056
Epoch  300/100000 Cost: 0.799744
Epoch  400/100000 Cost: 0.799432
Epoch  500/100000 Cost: 0.799123
Epoch  600/100000 Cost: 0.798817
Epoch  700/100000 Cost: 0.798523
Epoch  800/100000 Cost: 0.798227
Epoch  900/100000 Cost: 0.797934
Epoch 1000/100000 Cost: 0.797640
Epoch 1100/100000 Cost: 0.797349
Epoch 1200/100000 Cost: 0.797057
Epoch 1300/100000 Cost: 0.796766
Epoch 1400/100000 Cost: 0.796477
Epoch 1500/100000 Cost: 0.796188
Epoch 1600/100000 Cost: 0.795899
Epoch 1700/100000 Cost: 0.795611
Epoch 1800/100000 Cost: 0.795325
Epoch 1900/100000 Cost: 0.795041
Epoch 2000/100000 Cost: 0.794759
Epoch 2100/100000 Cost: 0.794479
Epoch 2200/100000 Cost: 0.794197
Epoch 2300/100000 Cost: 0.793918
Epoch 2400/100000 Cost: 0.793637
Epoch 2500/100000 Cost: 0.793369
Epoch 2600/100000 Cost: 0.793101
Epoch 2700/100000 Cost: 0.792835
Epoch 2800/100000 Cost: 0.792570
Epoch 2900/100000 Cost: 0.792304
Epoch 3000

Epoch 24500/100000 Cost: 0.756862
Epoch 24600/100000 Cost: 0.756765
Epoch 24700/100000 Cost: 0.756668
Epoch 24800/100000 Cost: 0.756574
Epoch 24900/100000 Cost: 0.756477
Epoch 25000/100000 Cost: 0.756380
Epoch 25100/100000 Cost: 0.756283
Epoch 25200/100000 Cost: 0.756189
Epoch 25300/100000 Cost: 0.756093
Epoch 25400/100000 Cost: 0.755997
Epoch 25500/100000 Cost: 0.755901
Epoch 25600/100000 Cost: 0.755807
Epoch 25700/100000 Cost: 0.755712
Epoch 25800/100000 Cost: 0.755616
Epoch 25900/100000 Cost: 0.755522
Epoch 26000/100000 Cost: 0.755429
Epoch 26100/100000 Cost: 0.755334
Epoch 26200/100000 Cost: 0.755239
Epoch 26300/100000 Cost: 0.755145
Epoch 26400/100000 Cost: 0.755053
Epoch 26500/100000 Cost: 0.754963
Epoch 26600/100000 Cost: 0.754876
Epoch 26700/100000 Cost: 0.754786
Epoch 26800/100000 Cost: 0.754700
Epoch 26900/100000 Cost: 0.754612
Epoch 27000/100000 Cost: 0.754526
Epoch 27100/100000 Cost: 0.754437
Epoch 27200/100000 Cost: 0.754351
Epoch 27300/100000 Cost: 0.754266
Epoch 27400/10

Epoch 48900/100000 Cost: 0.740361
Epoch 49000/100000 Cost: 0.740312
Epoch 49100/100000 Cost: 0.740266
Epoch 49200/100000 Cost: 0.740216
Epoch 49300/100000 Cost: 0.740170
Epoch 49400/100000 Cost: 0.740122
Epoch 49500/100000 Cost: 0.740075
Epoch 49600/100000 Cost: 0.740027
Epoch 49700/100000 Cost: 0.739979
Epoch 49800/100000 Cost: 0.739933
Epoch 49900/100000 Cost: 0.739885
Epoch 50000/100000 Cost: 0.739839
Epoch 50100/100000 Cost: 0.739790
Epoch 50200/100000 Cost: 0.739743
Epoch 50300/100000 Cost: 0.739696
Epoch 50400/100000 Cost: 0.739649
Epoch 50500/100000 Cost: 0.739602
Epoch 50600/100000 Cost: 0.739555
Epoch 50700/100000 Cost: 0.739507
Epoch 50800/100000 Cost: 0.739461
Epoch 50900/100000 Cost: 0.739414
Epoch 51000/100000 Cost: 0.739368
Epoch 51100/100000 Cost: 0.739320
Epoch 51200/100000 Cost: 0.739273
Epoch 51300/100000 Cost: 0.739226
Epoch 51400/100000 Cost: 0.739180
Epoch 51500/100000 Cost: 0.739132
Epoch 51600/100000 Cost: 0.739086
Epoch 51700/100000 Cost: 0.739038
Epoch 51800/10

Epoch 73200/100000 Cost: 0.730077
Epoch 73300/100000 Cost: 0.730039
Epoch 73400/100000 Cost: 0.730002
Epoch 73500/100000 Cost: 0.729965
Epoch 73600/100000 Cost: 0.729927
Epoch 73700/100000 Cost: 0.729889
Epoch 73800/100000 Cost: 0.729853
Epoch 73900/100000 Cost: 0.729816
Epoch 74000/100000 Cost: 0.729780
Epoch 74100/100000 Cost: 0.729740
Epoch 74200/100000 Cost: 0.729703
Epoch 74300/100000 Cost: 0.729667
Epoch 74400/100000 Cost: 0.729630
Epoch 74500/100000 Cost: 0.729592
Epoch 74600/100000 Cost: 0.729554
Epoch 74700/100000 Cost: 0.729518
Epoch 74800/100000 Cost: 0.729480
Epoch 74900/100000 Cost: 0.729443
Epoch 75000/100000 Cost: 0.729406
Epoch 75100/100000 Cost: 0.729369
Epoch 75200/100000 Cost: 0.729332
Epoch 75300/100000 Cost: 0.729294
Epoch 75400/100000 Cost: 0.729255
Epoch 75500/100000 Cost: 0.729221
Epoch 75600/100000 Cost: 0.729183
Epoch 75700/100000 Cost: 0.729146
Epoch 75800/100000 Cost: 0.729108
Epoch 75900/100000 Cost: 0.729072
Epoch 76000/100000 Cost: 0.729034
Epoch 76100/10

Epoch 97400/100000 Cost: 0.721290
Epoch 97500/100000 Cost: 0.721256
Epoch 97600/100000 Cost: 0.721219
Epoch 97700/100000 Cost: 0.721185
Epoch 97800/100000 Cost: 0.721151
Epoch 97900/100000 Cost: 0.721116
Epoch 98000/100000 Cost: 0.721079
Epoch 98100/100000 Cost: 0.721045
Epoch 98200/100000 Cost: 0.721010
Epoch 98300/100000 Cost: 0.720976
Epoch 98400/100000 Cost: 0.720941
Epoch 98500/100000 Cost: 0.720906
Epoch 98600/100000 Cost: 0.720872
Epoch 98700/100000 Cost: 0.720835
Epoch 98800/100000 Cost: 0.720801
Epoch 98900/100000 Cost: 0.720765
Epoch 99000/100000 Cost: 0.720731
Epoch 99100/100000 Cost: 0.720696
Epoch 99200/100000 Cost: 0.720663
Epoch 99300/100000 Cost: 0.720628
Epoch 99400/100000 Cost: 0.720592
Epoch 99500/100000 Cost: 0.720559
Epoch 99600/100000 Cost: 0.720522
Epoch 99700/100000 Cost: 0.720486
Epoch 99800/100000 Cost: 0.720452
Epoch 99900/100000 Cost: 0.720417
Epoch 100000/100000 Cost: 0.720383


In [21]:
# new_var=torch.FloatTensor([[73,80,75]])
new_var=torch.FloatTensor([[6,2]])
pred_y=model(new_var)
print(pred_y)
# print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

tensor([[16.9867]], grad_fn=<AddmmBackward0>)


In [81]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


# 05. 클래스로 파이토치 모델 구현하기
## 단순 선형 회귀 모델

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
torch.manual_seed(1)

In [7]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

In [9]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)
        
    def forward(self, x):
        return self.linear(x)
    
model=LinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [12]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    
    cost.backward()
    
    optimizer.step()
    
    if epoch%100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 18.562185
Epoch  100/2000 Cost: 0.128051
Epoch  200/2000 Cost: 0.079128
Epoch  300/2000 Cost: 0.048896
Epoch  400/2000 Cost: 0.030215
Epoch  500/2000 Cost: 0.018671
Epoch  600/2000 Cost: 0.011538
Epoch  700/2000 Cost: 0.007129
Epoch  800/2000 Cost: 0.004406
Epoch  900/2000 Cost: 0.002722
Epoch 1000/2000 Cost: 0.001682
Epoch 1100/2000 Cost: 0.001040
Epoch 1200/2000 Cost: 0.000642
Epoch 1300/2000 Cost: 0.000397
Epoch 1400/2000 Cost: 0.000245
Epoch 1500/2000 Cost: 0.000152
Epoch 1600/2000 Cost: 0.000094
Epoch 1700/2000 Cost: 0.000058
Epoch 1800/2000 Cost: 0.000036
Epoch 1900/2000 Cost: 0.000022
Epoch 2000/2000 Cost: 0.000014


## 다중 선형 회귀 모델

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
torch.manual_seed(1)

In [13]:
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [14]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)
        
    def forward(self, x):
        return self.linear(x)

model=MultivariateLinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

In [15]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 39633.414062
Epoch  100/2000 Cost: 11.480746
Epoch  200/2000 Cost: 10.894592
Epoch  300/2000 Cost: 10.339335
Epoch  400/2000 Cost: 9.813351
Epoch  500/2000 Cost: 9.315010
Epoch  600/2000 Cost: 8.842962
Epoch  700/2000 Cost: 8.395753
Epoch  800/2000 Cost: 7.972028
Epoch  900/2000 Cost: 7.570637
Epoch 1000/2000 Cost: 7.190376
Epoch 1100/2000 Cost: 6.830142
Epoch 1200/2000 Cost: 6.488811
Epoch 1300/2000 Cost: 6.165472
Epoch 1400/2000 Cost: 5.859105
Epoch 1500/2000 Cost: 5.568909
Epoch 1600/2000 Cost: 5.293931
Epoch 1700/2000 Cost: 5.033408
Epoch 1800/2000 Cost: 4.786575
Epoch 1900/2000 Cost: 4.552718
Epoch 2000/2000 Cost: 4.331151
